// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohlgzwrhxxixubqjqqrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9obGd6d3JoeHhpeHVicWpxcXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODEwOTEsImV4cCI6MjA3MjM1NzA5MX0.HiBlOSs8MGGSwhLcpslDlym8rYdy5jIqI4Qr-pmnfio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});